return {
    Cursor = { fg = 'MAGENTA', bg = 'WHITE' },
    Visual = { reverse = true },
    CursorLine = { bg = 'BLACK' },
    CursorColumn = { bg = 'BLACK' },
    ColorColumn = { bg = 'darker_gray' },
    LineNr = { fg = 'dark_gray', bg = 'BLACK' },
    VertSplit = { fg = 'dark_gray', bg = 'BLACK', bold = true },
    MatchParen = { fg = 'RED', reverse = true },
    StatusLine = { fg = 'WHITE', bg = 'darker_gray', bold = true },
    StatusLineNC = { fg = 'WHITE', bg = 'darker_gray' },
    Pmenu = { fg = 'WHITE', bg = 'darker_gray' },
    PmenuSel = { bg = 'BLACK' },
    IncSearch = { fg = 'BLACK', bg = 'YELLOW' },
    Search = { fg = 'YELLOW', bg = 'MAGENTA', underline = true },
    Directory = { fg = 'MAGENTA' },
    Folded = { fg = 'MAGENTA', bg = 'BLACK' },
    SignColumn = { fg = 'darker_gray', bg = 'BLACK' },
    FoldColmun = { fg = 'darker_gray', bg = 'BLACK' },
    Normal = { fg = 'WHITE', bg = 'BLACK' },
    Boolean = { fg = 'MAGENTA' },
    Character = { fg = 'MAGENTA' },
    Comment = { fg = 'light_gray' },
    Conditional = { fg = 'RED' },
    Constant = { fg = 'BLUE' },
    Define = { fg = 'RED' },

    healthError = { fg = 'RED' },
    healthSuccess = { fg = 'GREEN' },
    healthWarning = { fg = 'YELLOW' },

    GlyphPalette1 = { fg = 'RED' },
    GlyphPalette2 = { fg = 'YELLOW' },
    GlyphPalette3 = { fg = 'GREEN' },
    GlyphPalette4 = { fg = 'BLUE' },
    GlyphPalette6 = { fg = 'MAGENTA' },
    GlyphPalette7 = { fg = 'light_gray' },
    GlyphPalette9 = { fg = 'dark_gray' },

    rainbow1 = { fg = 'RED' },
    rainbow2 = { fg = 'YELLOW' },
    rainbow3 = { fg = 'GREEN' },
    rainbow4 = { fg = 'BLUE' },
    rainbow5 = { fg = 'MAGENTA' },
    rainbow6 = { fg = 'darker_gray' },

    RainbowDelimiterYellow = { fg = 'YELLOW' },
    RainbowDelimiterBlue = { fg = 'BLUE' },
    RainbowDelimiterOrange = { fg = 'RED' },
    RainbowDelimiterGreen = { fg = 'GREEN' },
    RainbowDelimiterViolet = { fg = 'MAGENTA' },
    RainbowDelimiterCyan = { fg = 'BLUE' },
    RainbowDelimiterRed = { fg = 'RED' },

    DiffAdd = { fg = 'WHITE', bg = 'GREEN', bold = true },
    DiffDelete = { fg = 'RED', bold = true },

    DiffLine = { fg = 'MAGENTA', italic = true },
    DiffText = { fg = 'WHITE', bg = 'BLUE', bold = true },
    diffSubName = { fg = 'MAGENTA', bg = 'BLACK', bold = true },

    GitSignsAdd = { bg = 'GREEN' },
    GitSignsRemoved = { bg = 'RED' },
    GitSignsChange = { bg = 'BLUE' },
    DiffChange = { bg = 'BLUE' },

    DiffAdded = { fg = 'GREEN' },
    DiffRemoved = { fg = 'RED' },

    fugitiveHunk = { fg = 'light_gray', italic = true },

    fugitiveUntrackedHeading = { fg = 'RED', bold = true, italic = false },
    fugitiveUnstagedHeading = { fg = 'BLUE', bold = true, italic = false },
    fugitiveStagedHeading = { fg = 'MAGENTA', bold = true, italic = false },

    fugitiveUntrackedSection = { fg = 'WHITE', italic = true },
    fugitiveUnstagedSection = { fg = 'WHITE', italic = true },
    fugitiveStagedSection = { fg = 'WHITE', italic = true },

    fugitiveUntrackedModifier = { fg = 'RED', bold = true, italic = false },
    fugitiveUnstagedModifier = { fg = 'BLUE', bold = true, italic = false },
    fugitiveStagedModifier = { fg = 'MAGENTA', bold = true, italic = false },

    ErrorMsg = { fg = 'WHITE', bg = 'RED' },
    WarningMsg = { fg = 'WHITE', bg = 'RED' },
    Float = { fg = 'MAGENTA' },
    Function = { fg = 'BLUE' },
    Identifier = { fg = 'GREEN', italic = true },
    Keyword = { fg = 'RED' },
    Label = { fg = 'YELLOW' },
    NonText = { fg = 'darker_gray', bg = 'BLACK' },
    Number = { fg = 'MAGENTA' },
    Operator = { fg = 'RED' },
    PreProc = { fg = 'RED' },
    Special = { fg = 'WHITE' },
    SpecialKey = { fg = 'darker_gray', bg = 'BLACK' },
    Statement = { fg = 'RED' },
    StorageClass = { fg = 'GREEN', italic = true },
    String = { fg = 'YELLOW' },
    Tag = { fg = 'RED' },
    Title = { fg = 'WHITE', bold = true },
    Todo = { bg = 'MAGENTA', bold = true },
    Type = { fg = 'GREEN' },
    Underlined = { underline = true },

    TabLineFill = { fg = 'darker_gray', bg = 'BLACK' },
    TabLine = { fg = 'GRAY', bg = 'BLACK' },
    TabLineSel = { fg = 'WHITE', bg = 'BLACK' },

    rubyClass = { fg = 'RED' },
    rubyFunction = { fg = 'BLUE' },
    rubyInterpolationDelimiter = { fg = 'BLUE', italic = true },
    rubySymbol = { fg = 'MAGENTA' },
    rubyConstant = { fg = 'GREEN', italic = true },
    rubyStringDelimiter = { fg = 'YELLOW' },
    rubyBlockParameter = { fg = 'YELLOW', italic = true },
    rubyInstanceVariable = { fg = 'RED' },
    rubyInclude = { fg = 'RED' },
    rubyGlobalVariable = { fg = 'BLUE' },
    rubyRegexp = { fg = 'YELLOW' },
    rubyRegexpDelimiter = { fg = 'YELLOW' },
    rubyEscape = { fg = 'MAGENTA' },
    rubyControl = { fg = 'RED' },
    rubyClassVariable = { fg = 'YELLOW' },
    rubyOperator = { fg = 'RED' },
    rubyException = { fg = 'RED' },
    rubyPseudoVariable = { fg = 'MAGENTA' },
    rubyRailsUserClass = { fg = 'GREEN', italic = true },
    rubyRailsARAssociationMethod = { fg = 'GREEN' },
    rubyRailsARMethod = { fg = 'GREEN' },
    rubyRailsRenderMethod = { fg = 'GREEN' },
    rubyRailsMethod = { fg = 'GREEN' },
    erubyDelimiter = { fg = 'BLUE', italic = true },
    erubyComment = { fg = 'MAGENTA' },
    erubyRailsMethod = { fg = 'GREEN' },

    htmlTag = { fg = 'RED' , italic = true },
    htmlEndTag = { fg = 'RED' , italic = true },
    htmlTagName = { fg = 'BLUE' },
    htmlArg = { fg = 'YELLOW' },
    htmlSpecialChar = { fg = 'MAGENTA' },

    javaScriptFunction = { fg = 'GREEN', italic = true },
    javaScriptRailsFunction = { fg = 'GREEN' },
    javaScriptBraces = { fg = 'GREEN' },

    yamlKey = { fg = 'RED' },
    yamlAnchor = { fg = 'MAGENTA' },
    yamlAlias = { fg = 'BLUE' },
    yamlDocumentHeader = { fg = 'YELLOW' },

    cssURL = { fg = 'YELLOW', italic = true },
    cssFunctionName = { fg = 'GREEN' },
    cssColor = { fg = 'MAGENTA' },
    cssPseudoClassId = { fg = 'BLUE' },
    cssClassName = { fg = 'BLUE' },
    cssValueLength = { fg = 'MAGENTA' },
    cssCommonAttr = { fg = 'BLUE' },
    cssBraces = { fg = 'GREEN' },

    elixirAtom = { fg = 'GREEN', italic = true },
    elixirModuleDeclaration = { fg = 'GREEN', italic = true },
    elixirAlias = { fg = 'GREEN', italic = true },
    elixirInterpolationDelimiter = { fg = 'BLUE' },
    elixirStringDelimiter = { fg = 'YELLOW' },

    vimGroupName = { fg = 'GREEN' },
    vimGroup = { fg = 'GREEN' },
    vimOption = { fg = 'GREEN' },
    -- vimHiCtermFgBg = {},
    -- vimHiGuiFgBg = {}
}
